name: CI/CD

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "bot-discord-codgox"

      - name: Execute commands on the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            ls -a
            cd bot-discord-codgox
            rm .env -f
            touch .env
            echo DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} >> .env
            echo DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }} >> .env
            echo SCRUM_CHANNEL_ID=${{ secrets.SCRUM_CHANNEL_ID }} >> .env
            echo WORKFLOW_CHANNEL_ID=${{ secrets.WORKFLOW_CHANNEL_ID }} >> .env
            echo DEVELOPMENT_ROLE_ID=${{ secrets.DEVELOPMENT_ROLE_ID }} >> .env
            echo WORKFLOW_ROLE_ID=${{ secrets.WORKFLOW_ROLE_ID }} >> .env
            npm ci
            npm run start
